/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** ログイン */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** ログアウト */
    post: operations['auth.logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** ユーザー登録 */
    post: operations['auth.register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** トークンのリフレッシュ */
    post: operations['auth.refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 通知一覧取得 */
    get: operations['notification.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 未読通知数取得 */
    get: operations['notification.unreadCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** すべての通知を既読にする */
    put: operations['notification.markAllAsRead'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notifications/{notification}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 通知を既読にする */
    put: operations['notification.markAsRead'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** タスク一覧取得 */
    get: operations['tasks.index'];
    put?: never;
    /** 新規タスク作成 */
    post: operations['tasks.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tasks/{task}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** タスク単体取得 */
    get: operations['tasks.show'];
    /** タスク更新 */
    put: operations['tasks.update'];
    post?: never;
    /** タスク削除 */
    delete: operations['tasks.destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tasks/{task}/actions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** タスクに対応するアクション一覧 */
    get: operations['tasks.actions.index'];
    put?: never;
    /** タスクに対応するアクション作成 */
    post: operations['tasks.actions.store'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tasks/{task}/actions/{action}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** タスクに対応するアクション更新 */
    put: operations['tasks.actions.update'];
    post?: never;
    /** タスクに対応するアクション削除 */
    delete: operations['tasks.actions.destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 自身のユーザ取得 */
    get: operations['user.me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ユーザ一覧取得 */
    get: operations['users.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/{user}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['users.update'];
    post?: never;
    delete: operations['users.destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/{user}/icon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * ユーザーアイコンの配信
     * @description 認証不要。`/api` 配下から返すことで、配信用のインフラを別に用意せずに済ませている。
     */
    get: operations['users.icon.show'];
    put?: never;
    /**
     * ユーザーアイコンのアップロード
     * @description multipart/form-data で `icon` を送る。既にアイコンがある場合は差し替える。
     */
    post: operations['userIcon.store'];
    /** ユーザーアイコンの削除 */
    delete: operations['userIcon.destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 自身のタスク一覧取得 */
    get: operations['users.me.tasks.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** LoginCollection */
    LoginCollection: {
      token: string[];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** NotificationResource */
    NotificationResource: {
      id: number;
      title: string;
      message: string | null;
      type: string;
      related_task_id: number | null;
      is_read: boolean;
      /** Format: date-time */
      read_at: string | null;
      /** Format: date-time */
      created_at: string | null;
    };
    /** RegisterResource */
    RegisterResource: {
      user: {
        id: string;
        name: string;
        email: string;
        email_verified_at: string;
        created_at: string;
        updated_at: string;
        deleted_at: string;
      };
      token: string;
    };
    /** StoreTaskActionRequest */
    StoreTaskActionRequest: {
      name: string;
      is_done?: boolean;
    };
    /** StoreTaskRequest */
    StoreTaskRequest: {
      title: string;
      is_public: boolean;
      description?: string | null;
      /** Format: date-time */
      expired_at?: string | null;
      assigned_user_ids?: number[] | null;
    };
    /** TaskActionResource */
    TaskActionResource: {
      id: number;
      task_id: number;
      name: string;
      is_done: boolean;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
      /** Format: date-time */
      deleted_at: string | null;
    };
    /** TaskResource */
    TaskResource: {
      id: number;
      title: string;
      description: string | null;
      is_public: boolean;
      is_done: boolean;
      /** Format: date-time */
      expired_at: string | null;
      created_user_id: number;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
      created_user: components['schemas']['UserResource'];
      assigned_users: components['schemas']['UserResource'][];
    };
    /** UpdateTaskActionRequest */
    UpdateTaskActionRequest: {
      name?: string;
      is_done?: boolean;
    };
    /** UpdateTaskRequest */
    UpdateTaskRequest: {
      title?: string;
      is_public?: boolean;
      /** Format: date-time */
      expired_at?: string | null;
      description?: string | null;
      is_done?: boolean;
      assigned_user_ids?: number[] | null;
    };
    /** UpdateUserIconRequest */
    UpdateUserIconRequest: {
      /**
       * Format: binary
       * @description Maximum file size: 2048 kilobytes.
       */
      icon: string;
    };
    /** UpdateUserRequest */
    UpdateUserRequest: {
      name?: string;
      /** Format: email */
      email?: string;
      password?: string;
      password_confirmation?: string;
    };
    /** UserResource */
    UserResource: {
      id: number;
      name: string;
      email: string;
      /** Format: date-time */
      email_verified_at: string | null;
      icon_url: string | null;
      /** Format: date-time */
      created_at: string | null;
      /** Format: date-time */
      updated_at: string | null;
    };
  };
  responses: {
    /** @description Validation error */
    ValidationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Errors overview. */
          message: string;
          /** @description A detailed description of each field that failed validation. */
          errors: {
            [key: string]: string[];
          };
        };
      };
    };
    /** @description Not found */
    ModelNotFoundException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string;
        };
      };
    };
    /** @description Unauthenticated */
    AuthenticationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string;
        };
      };
    };
    /** @description Authorization error */
    AuthorizationException: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          /** @description Error overview. */
          message: string;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description `LoginCollection` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginCollection'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            error: 'Unauthorized';
          };
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'auth.logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            message: 'Successfully logged out';
          };
        };
      };
    };
  };
  'auth.register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          /** Format: email */
          email: string;
          password: string;
          password_confirmation: string;
        };
      };
    };
    responses: {
      /** @description `RegisterResource` */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterResource'];
        };
      };
      422: components['responses']['ValidationException'];
    };
  };
  'auth.refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            token: string;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            error: 'Token not provided';
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            error: 'Could not refresh token';
            detail: string;
          };
        };
      };
    };
  };
  'notification.index': {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            notifications: components['schemas']['NotificationResource'][];
            unread_count: number;
            page: number;
            size: number;
            total_pages: number;
            total_elements: number;
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'notification.unreadCount': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            unread_count: number;
          };
        };
      };
      401: components['responses']['AuthenticationException'];
    };
  };
  'notification.markAllAsRead': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            message: 'All notifications marked as read';
          };
        };
      };
      401: components['responses']['AuthenticationException'];
    };
  };
  'notification.markAsRead': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The notification ID */
        notification: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            notification: components['schemas']['NotificationResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Error overview. */
            message: string;
          };
        };
      };
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'tasks.index': {
    parameters: {
      query?: {
        is_public?: boolean | null;
        is_done?: boolean | null;
        expired_before?: string | null;
        expired_after?: string | null;
        created_user_id?: number | null;
        'created_user_ids[]'?: number[];
        assigned_user_id?: number | null;
        'assigned_user_ids[]'?: number[];
        sort_by?: 'title' | 'expired_at' | 'created_at' | 'updated_at' | null;
        sort_order?: 'asc' | 'desc' | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tasks: components['schemas']['TaskResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'tasks.store': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreTaskRequest'];
      };
    };
    responses: {
      /** @description `TaskResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            task: components['schemas']['TaskResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      422: components['responses']['ValidationException'];
    };
  };
  'tasks.show': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `TaskResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            task: components['schemas']['TaskResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'tasks.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateTaskRequest'];
      };
    };
    responses: {
      /** @description `TaskResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            task: components['schemas']['TaskResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      404: components['responses']['ModelNotFoundException'];
      422: components['responses']['ValidationException'];
    };
  };
  'tasks.destroy': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['AuthenticationException'];
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'tasks.actions.index': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            actions: components['schemas']['TaskActionResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'tasks.actions.store': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StoreTaskActionRequest'];
      };
    };
    responses: {
      /** @description `TaskActionResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskActionResource'];
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      404: components['responses']['ModelNotFoundException'];
      422: components['responses']['ValidationException'];
    };
  };
  'tasks.actions.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
        /** @description The action ID */
        action: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateTaskActionRequest'];
      };
    };
    responses: {
      /** @description `TaskActionResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskActionResource'];
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      404: components['responses']['ModelNotFoundException'];
      422: components['responses']['ValidationException'];
    };
  };
  'tasks.actions.destroy': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The task ID */
        task: number;
        /** @description The action ID */
        action: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['AuthenticationException'];
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'user.me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['UserResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
    };
  };
  'users.index': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            users: components['schemas']['UserResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
    };
  };
  'users.update': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The user ID */
        user: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['UserResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      404: components['responses']['ModelNotFoundException'];
      422: components['responses']['ValidationException'];
    };
  };
  'users.destroy': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The user ID */
        user: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['AuthenticationException'];
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'users.icon.show': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The user ID */
        user: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description URL はユーザーごとに固定で、更新時は icon_url の `?v=` が変わる。
       *     そのためブラウザには長めにキャッシュさせてよい
       */
      200: {
        headers: {
          'Transfer-Encoding': 'chunked';
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'userIcon.store': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The user ID */
        user: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['UpdateUserIconRequest'];
      };
    };
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['UserResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      403: components['responses']['AuthorizationException'];
      404: components['responses']['ModelNotFoundException'];
      422: components['responses']['ValidationException'];
    };
  };
  'userIcon.destroy': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The user ID */
        user: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `UserResource` */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['UserResource'];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      /** @description Access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Error overview. */
            message: string;
          };
        };
      };
      404: components['responses']['ModelNotFoundException'];
    };
  };
  'users.me.tasks.index': {
    parameters: {
      query?: {
        is_public?: boolean | null;
        is_done?: boolean | null;
        expired_before?: string | null;
        expired_after?: string | null;
        created_user_id?: number | null;
        'created_user_ids[]'?: number[];
        assigned_user_id?: number | null;
        'assigned_user_ids[]'?: number[];
        sort_by?: 'title' | 'expired_at' | 'created_at' | 'updated_at' | null;
        sort_order?: 'asc' | 'desc' | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tasks: components['schemas']['TaskResource'][];
          };
        };
      };
      401: components['responses']['AuthenticationException'];
      422: components['responses']['ValidationException'];
    };
  };
}
